import cv2

# Load status images for each boss status
# These images are used to identify the status of a boss in the game
img_status = {
    'STATUS_LT': cv2.imread('images/boss-status/longer-time.png'),
    'STATUS_ST': cv2.imread('images/boss-status/short-time.png'),
    'STATUS_RS': cv2.imread('images/boss-status/refreshing-soon.png'),
    'STATUS_APP': cv2.imread('images/boss-status/appeared.png'),
}

img_lookup = {
    #buttons folder
    'buttons/banner-close-button': cv2.imread('images/buttons/banner-close-button.png'),
    'buttons/battle-screen-button': cv2.imread('images/buttons/battle-screen-button.png'),
    'buttons/close-button': cv2.imread('images/buttons/close-button.png'),
    'buttons/mini-tab-button': cv2.imread('images/buttons/mini-tab-button.png'),
    'buttons/mvp-screen-button': cv2.imread('images/buttons/mvp-screen-button.png'),
    'buttons/mvp-tab-button': cv2.imread('images/buttons/mvp-tab-button.png'),
    'buttons/unhide-icons-button': cv2.imread('images/buttons/unhide-icons-button.png'),
    'buttons/map-close-button': cv2.imread('images/buttons/map-close-button.png'),
    'buttons/kpass-close-button': cv2.imread('images/buttons/kpass-close-button.png'),
    'buttons/topup-close-button': cv2.imread('images/buttons/topup-close-button.png'),
    'buttons/disconnected-button': cv2.imread('images/buttons/disconnected-button.png'),
    'buttons/update-button': cv2.imread('images/buttons/update-button.png'),
    'buttons/home-screen-button': cv2.imread('images/buttons/home-screen-button.png'),
    'buttons/enter-game-button': cv2.imread('images/buttons/enter-game-button.png'),
    'buttons/select-character-button': cv2.imread('images/buttons/select-character-button.png'),
    #screens folder
    'screens/mvp-screen': cv2.imread('images/screens/mvp-screen.png'),
    'screens/battle-result-screen': cv2.imread('images/screens/battle-result-screen.png'),
    'screens/disconnected-screen': cv2.imread('images/screens/disconnected-screen.png'),
    'screens/in-game-popup-screen': cv2.imread('images/screens/in-game-popup-screen.png'),
    'screens/kingdom-pass-screen': cv2.imread('images/screens/kingdom-pass-screen.png'),
    'screens/topup-screen': cv2.imread('images/screens/topup-screen.png'),
    'screens/map-screen': cv2.imread('images/screens/map-screen.png'),
    'screens/mini-tab-screen': cv2.imread('images/screens/mini-tab-screen.png'),
    'screens/mvp-button-screen': cv2.imread('images/screens/mvp-button-screen.png'),
    'screens/mvp-tab-screen': cv2.imread('images/screens/mvp-tab-screen.png'),
    'screens/new-update-screen': cv2.imread('images/screens/new-update-screen.png'),
    'screens/retrieve-screen': cv2.imread('images/screens/retrieve-screen.png'),
    'screens/unhide-button-screen': cv2.imread('images/screens/unhide-button-screen.png'),
    'screens/welcome-popup-screen': cv2.imread('images/screens/welcome-popup-screen.png'),
    #boss-image folder
    'boss-image/amon-ra-wallpaper': cv2.imread('images/boss-image/amon-ra-wallpaper.png'),
    'boss-image/angeling-wallpaper': cv2.imread('images/boss-image/angeling-wallpaper.png'),
    'boss-image/arc-angeling-wallpaper': cv2.imread('images/boss-image/arc-angeling-wallpaper.png'),
    'boss-image/carnage-kabuto-wallpaper': cv2.imread('images/boss-image/carnage-kabuto-wallpaper.png'),
    'boss-image/chimera-wallpaper': cv2.imread('images/boss-image/chimera-wallpaper.png'),
    'boss-image/coelacanth-wallpaper': cv2.imread('images/boss-image/coelacanth-wallpaper.png'),
    'boss-image/dark-priest-wallpaper': cv2.imread('images/boss-image/dark-priest-wallpaper.png'),
    'boss-image/deviling-wallpaper': cv2.imread('images/boss-image/deviling-wallpaper.png'),
    'boss-image/doppelganger-wallpaper': cv2.imread('images/boss-image/doppelganger-wallpaper.png'),
    'boss-image/dragon-fly-wallpaper': cv2.imread('images/boss-image/dragon-fly-wallpaper.png'),
    'boss-image/eclipse-wallpaper': cv2.imread('images/boss-image/eclipse-wallpaper.png'),
    'boss-image/eddga-wallpaper': cv2.imread('images/boss-image/eddga-wallpaper.png'),
    'boss-image/fallen-bishop-wallpaper': cv2.imread('images/boss-image/fallen-bishop-wallpaper.png'),
    'boss-image/ghostring-wallpaper': cv2.imread('images/boss-image/ghostring-wallpaper.png'),
    'boss-image/gioia-wallpaper': cv2.imread('images/boss-image/gioia-wallpaper.png'),
    'boss-image/king-dramoh-wallpaper': cv2.imread('images/boss-image/king-dramoh-wallpaper.png'),
    'boss-image/kraken-wallpaper': cv2.imread('images/boss-image/kraken-wallpaper.png'),
    'boss-image/lord-of-the-dead-wallpaper': cv2.imread('images/boss-image/lord-of-the-dead-wallpaper.png'),
    'boss-image/lost-dragon-wallpaper': cv2.imread('images/boss-image/lost-dragon-wallpaper.png'),
    'boss-image/mastering-wallpaper': cv2.imread('images/boss-image/mastering-wallpaper.png'),
    'boss-image/maya-wallpaper': cv2.imread('images/boss-image/maya-wallpaper.png'),
    'boss-image/mistress-wallpaper': cv2.imread('images/boss-image/mistress-wallpaper.png'),
    'boss-image/morroc-wallpaper': cv2.imread('images/boss-image/morroc-wallpaper.png'),
    'boss-image/mosquito-girl-wallpaper': cv2.imread('images/boss-image/mosquito-girl-wallpaper.png'),
    'boss-image/mysteltainn-wallpaper': cv2.imread('images/boss-image/mysteltainn-wallpaper.png'),
    'boss-image/naght-sieger-wallpaper': cv2.imread('images/boss-image/naght-sieger-wallpaper.png'),
    'boss-image/necromancer-wallpaper': cv2.imread('images/boss-image/necromancer-wallpaper.png'),
    'boss-image/observation-wallpaper': cv2.imread('images/boss-image/observation-wallpaper.png'),
    'boss-image/ogretooth-wallpaper': cv2.imread('images/boss-image/ogretooth-wallpaper.png'),
    'boss-image/orc-disaster-wallpaper': cv2.imread('images/boss-image/orc-disaster-wallpaper.png'),
    'boss-image/orc-hero-wallpaper': cv2.imread('images/boss-image/orc-hero-wallpaper.png'),
    'boss-image/orc-lord-wallpaper': cv2.imread('images/boss-image/orc-lord-wallpaper.png'),
    'boss-image/time-holder-wallpaper': cv2.imread('images/boss-image/time-holder-wallpaper.png'),
    'boss-image/pharaoh-wallpaper': cv2.imread('images/boss-image/pharaoh-wallpaper.png'),
    'boss-image/phreeoni-wallpaper': cv2.imread('images/boss-image/phreeoni-wallpaper.png'),
    'boss-image/skeggiold-wallpaper': cv2.imread('images/boss-image/skeggiold-wallpaper.png'),
    'boss-image/storm-dragon-wallpaper': cv2.imread('images/boss-image/storm-dragon-wallpaper.png'),
    'boss-image/tao-gunka-wallpaper': cv2.imread('images/boss-image/tao-gunka-wallpaper.png'),
    'boss-image/toad-wallpaper': cv2.imread('images/boss-image/toad-wallpaper.png'),
    'boss-image/vagabond-wolf-wallpaper': cv2.imread('images/boss-image/vagabond-wolf-wallpaper.png'),
}

img_sidebar = {
    'amon-ra.png': cv2.imread('images/boss-sidebar/amon-ra.png'),
    'angeling.png': cv2.imread('images/boss-sidebar/angeling.png'),
    'arc-angeling.png': cv2.imread('images/boss-sidebar/arc-angeling.png'),
    'carnage-kabuto.png': cv2.imread('images/boss-sidebar/carnage-kabuto.png'),
    'chimera.png': cv2.imread('images/boss-sidebar/chimera.png'),
    'coelacanth.png': cv2.imread('images/boss-sidebar/coelacanth.png'),
    'dark-priest.png': cv2.imread('images/boss-sidebar/dark-priest.png'),
    'deviling.png': cv2.imread('images/boss-sidebar/deviling.png'),
    'doppelganger.png': cv2.imread('images/boss-sidebar/doppelganger.png'),
    'dragon-fly.png': cv2.imread('images/boss-sidebar/dragon-fly.png'),
    'eclipse.png': cv2.imread('images/boss-sidebar/eclipse.png'),
    'eddga.png': cv2.imread('images/boss-sidebar/eddga.png'),
    'fallen-bishop.png': cv2.imread('images/boss-sidebar/fallen-bishop.png'),
    'ghostring.png': cv2.imread('images/boss-sidebar/ghostring.png'),
    'gioia.png': cv2.imread('images/boss-sidebar/gioia.png'),
    'king-dramoh.png': cv2.imread('images/boss-sidebar/king-dramoh.png'),
    'kraken.png': cv2.imread('images/boss-sidebar/kraken.png'),
    'lord-of-the-dead.png': cv2.imread('images/boss-sidebar/lord-of-the-dead.png'),
    'lost-dragon.png': cv2.imread('images/boss-sidebar/lost-dragon.png'),
    'mastering.png': cv2.imread('images/boss-sidebar/mastering.png'),
    'maya.png': cv2.imread('images/boss-sidebar/maya.png'),
    'mistress.png': cv2.imread('images/boss-sidebar/mistress.png'),
    'morroc.png': cv2.imread('images/boss-sidebar/morroc.png'),
    'mosquito-girl.png': cv2.imread('images/boss-sidebar/mosquito-girl.png'),
    'mysteltainn.png': cv2.imread('images/boss-sidebar/mysteltainn.png'),
    'naght-sieger.png': cv2.imread('images/boss-sidebar/naght-sieger.png'),
    'necromancer.png': cv2.imread('images/boss-sidebar/necromancer.png'),
    'observation.png': cv2.imread('images/boss-sidebar/observation.png'),
    'ogretooth.png': cv2.imread('images/boss-sidebar/ogretooth.png'),
    'orc-disaster.png': cv2.imread('images/boss-sidebar/orc-disaster.png'),
    'orc-hero.png': cv2.imread('images/boss-sidebar/orc-hero.png'),
    'orc-lord.png': cv2.imread('images/boss-sidebar/orc-lord.png'),
    'time-holder.png': cv2.imread('images/boss-sidebar/time-holder.png'),
    'pharaoh.png': cv2.imread('images/boss-sidebar/pharaoh.png'),
    'phreeoni.png': cv2.imread('images/boss-sidebar/phreeoni.png'),
    'skeggiold.png': cv2.imread('images/boss-sidebar/skeggiold.png'),
    'storm-dragon.png': cv2.imread('images/boss-sidebar/storm-dragon.png'),
    'tao-gunka.png': cv2.imread('images/boss-sidebar/tao-gunka.png'),
    'toad.png': cv2.imread('images/boss-sidebar/toad.png'),
    'vagabond-wolf.png': cv2.imread('images/boss-sidebar/vagabond-wolf.png'),
}

def convert_to_grayscale(images_dict):
    for key, img in images_dict.items():
        images_dict[key] = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
convert_to_grayscale(img_status)
convert_to_grayscale(img_lookup)
convert_to_grayscale(img_sidebar)